import { PDFDocument, PDFPage, PDFFont, rgb, StandardFonts, PageSizes } from 'pdf-lib';
import { Resvg } from '@resvg/resvg-js';
import type { PatternData, PaletteEntry } from './types';

export interface PdfOptions {
  pattern: PatternData;
  chartSvg: string;
}

const PAGE_WIDTH = PageSizes.A4[0];  // 595.28
const PAGE_HEIGHT = PageSizes.A4[1]; // 841.89
const MARGIN = 40;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const clean = hex.replace('#', '').padEnd(6, '0');
  return {
    r: parseInt(clean.slice(0, 2), 16) / 255,
    g: parseInt(clean.slice(2, 4), 16) / 255,
    b: parseInt(clean.slice(4, 6), 16) / 255,
  };
}

function rleRow(row: number[], palette: PaletteEntry[]): string {
  if (row.length === 0) return '(empty)';
  const parts: string[] = [];
  let current = row[0];
  let count = 1;
  for (let i = 1; i < row.length; i++) {
    if (row[i] === current) {
      count++;
    } else {
      const sym = palette.find((p) => p.index === current)?.symbol ?? String(current);
      parts.push(`${count} ${sym}`);
      current = row[i];
      count = 1;
    }
  }
  const sym = palette.find((p) => p.index === current)?.symbol ?? String(current);
  parts.push(`${count} ${sym}`);
  return parts.join(', ');
}

function wrapText(
  text: string,
  font: PDFFont,
  size: number,
  maxWidth: number,
): string[] {
  const words = text.split(' ');
  const lines: string[] = [];
  let currentLine = '';
  for (const word of words) {
    const candidate = currentLine ? `${currentLine} ${word}` : word;
    if (font.widthOfTextAtSize(candidate, size) <= maxWidth) {
      currentLine = candidate;
    } else {
      if (currentLine) lines.push(currentLine);
      // If a single word is wider than maxWidth, just push it as-is
      currentLine = word;
    }
  }
  if (currentLine) lines.push(currentLine);
  return lines;
}

export async function generatePatternPdf(opts: PdfOptions): Promise<Buffer> {
  const { pattern, chartSvg } = opts;

  const doc = await PDFDocument.create();
  const helvetica = await doc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await doc.embedFont(StandardFonts.HelveticaBold);

  const black = rgb(0, 0, 0);
  const gray = rgb(0.4, 0.4, 0.4);
  const lightGray = rgb(0.85, 0.85, 0.85);

  const footerText = `Pattern ID: ${pattern.patternId} — Generated by Crochet Pattern Generator`;

  function newPage(): PDFPage {
    return doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  }

  function drawFooter(page: PDFPage): void {
    page.drawText(footerText, {
      x: MARGIN,
      y: 18,
      size: 8,
      font: helvetica,
      color: gray,
    });
  }

  // ---------------------------------------------------------------------------
  // PAGE 1 — Title & Info
  // ---------------------------------------------------------------------------
  {
    const page = newPage();
    let y = PAGE_HEIGHT - MARGIN;

    page.drawText(pattern.title, {
      x: MARGIN,
      y,
      size: 28,
      font: helveticaBold,
      color: black,
    });
    y -= 40;

    page.drawText('Tapestry Crochet Pattern — Worsted Weight', {
      x: MARGIN,
      y,
      size: 14,
      font: helvetica,
      color: gray,
    });
    y -= 36;

    page.drawText(
      `Blanket size: ${pattern.dimensions.width}W \u00d7 ${pattern.dimensions.height}H stitches`,
      { x: MARGIN, y, size: 12, font: helvetica, color: black },
    );
    y -= 22;

    page.drawText('Gauge: 4 stitches / 5 rows per inch (worsted, 5.0mm hook)', {
      x: MARGIN,
      y,
      size: 12,
      font: helvetica,
      color: black,
    });
    y -= 22;

    const genDate = new Date(pattern.createdAt).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
    page.drawText(`Generated: ${genDate}`, {
      x: MARGIN,
      y,
      size: 12,
      font: helvetica,
      color: black,
    });

    drawFooter(page);
  }

  // ---------------------------------------------------------------------------
  // PAGE 2 — Color Legend & Yarn Inventory
  // ---------------------------------------------------------------------------
  {
    const page = newPage();
    let y = PAGE_HEIGHT - MARGIN;

    page.drawText('Color Legend & Yarn Requirements', {
      x: MARGIN,
      y,
      size: 18,
      font: helveticaBold,
      color: black,
    });
    y -= 32;

    // Column X positions
    const cols = {
      symbol:     MARGIN,
      colorName:  MARGIN + 48,
      suggestion: MARGIN + 148,
      hex:        MARGIN + 278,
      stitches:   MARGIN + 338,
      yards:      MARGIN + 395,
      skeins:     MARGIN + 450,
    };

    // Header row background
    page.drawRectangle({
      x: MARGIN,
      y: y - 4,
      width: CONTENT_WIDTH,
      height: 18,
      color: lightGray,
    });

    const headers: Array<[keyof typeof cols, string]> = [
      ['symbol',     'Symbol'],
      ['colorName',  'Color Name'],
      ['suggestion', 'Yarn Suggestion'],
      ['hex',        'Hex'],
      ['stitches',   'Stitches'],
      ['yards',      'Yards'],
      ['skeins',     'Skeins'],
    ];

    for (const [key, label] of headers) {
      page.drawText(label, { x: cols[key], y, size: 9, font: helveticaBold, color: black });
    }
    y -= 22;

    for (const entry of pattern.inventory) {
      const pal = pattern.palette.find((p) => p.index === entry.paletteIndex);
      if (!pal) continue;

      // Color swatch before symbol
      const c = hexToRgb(pal.hex);
      page.drawRectangle({
        x: cols.symbol,
        y: y - 2,
        width: 10,
        height: 10,
        color: rgb(c.r, c.g, c.b),
        borderColor: gray,
        borderWidth: 0.5,
      });
      page.drawText(pal.symbol, {
        x: cols.symbol + 14,
        y,
        size: 9,
        font: helvetica,
        color: black,
      });

      const colorName = (pal.name ?? 'Unknown').slice(0, 14);
      page.drawText(colorName, { x: cols.colorName, y, size: 9, font: helvetica, color: black });

      const suggestion =
        pal.yarnBrand && pal.yarnColorName
          ? `${pal.yarnBrand} ${pal.yarnColorName}`.slice(0, 18)
          : 'Worsted weight';
      page.drawText(suggestion, { x: cols.suggestion, y, size: 9, font: helvetica, color: black });

      page.drawText(pal.hex, { x: cols.hex, y, size: 9, font: helvetica, color: black });
      page.drawText(entry.totalStitches.toLocaleString(), {
        x: cols.stitches,
        y,
        size: 9,
        font: helvetica,
        color: black,
      });
      page.drawText(entry.yardsNeeded.toString(), {
        x: cols.yards,
        y,
        size: 9,
        font: helvetica,
        color: black,
      });
      page.drawText(entry.skeinsNeeded.toString(), {
        x: cols.skeins,
        y,
        size: 9,
        font: helvetica,
        color: black,
      });

      y -= 18;
    }

    y -= 16;
    page.drawText(
      '* Yardage estimates include 15% buffer. Worsted weight only. Buy one extra skein per color.',
      { x: MARGIN, y, size: 8, font: helvetica, color: gray },
    );

    drawFooter(page);
  }

  // ---------------------------------------------------------------------------
  // PAGE 3+ — Row-by-Row Instructions (bottom-to-top, max 50 rows per page)
  // ---------------------------------------------------------------------------
  {
    const ROWS_PER_PAGE = 50;
    const LINE_HEIGHT = 13;
    const totalRows = pattern.stitchGrid.length;

    for (let pageStart = 0; pageStart < totalRows; pageStart += ROWS_PER_PAGE) {
      const page = newPage();
      let y = PAGE_HEIGHT - MARGIN;

      if (pageStart === 0) {
        page.drawText('Row-by-Row Instructions (Bottom to Top)', {
          x: MARGIN,
          y,
          size: 18,
          font: helveticaBold,
          color: black,
        });
        y -= 32;
      }

      const pageEnd = Math.min(pageStart + ROWS_PER_PAGE, totalRows);

      for (let rowIdx = pageStart; rowIdx < pageEnd; rowIdx++) {
        const row = pattern.stitchGrid[rowIdx];
        const rleStr = rleRow(row, pattern.palette);
        const lineText = `Row ${rowIdx + 1}: ${rleStr}`;

        const wrappedLines = wrapText(lineText, helvetica, 9, CONTENT_WIDTH);
        for (const wLine of wrappedLines) {
          if (y < MARGIN + LINE_HEIGHT) break; // safety guard
          page.drawText(wLine, { x: MARGIN, y, size: 9, font: helvetica, color: black });
          y -= LINE_HEIGHT;
        }
      }

      drawFooter(page);
    }
  }

  // ---------------------------------------------------------------------------
  // LAST PAGE — Stitch Chart
  // ---------------------------------------------------------------------------
  {
    const page = newPage();
    let y = PAGE_HEIGHT - MARGIN;

    page.drawText('Stitch Chart', {
      x: MARGIN,
      y,
      size: 18,
      font: helveticaBold,
      color: black,
    });
    y -= 30;

    const pngBuffer = new Resvg(chartSvg).render().asPng();
    const pngImage = await doc.embedPng(pngBuffer);

    const maxW = CONTENT_WIDTH;
    const maxH = y - MARGIN - 20;
    const scale = Math.min(maxW / pngImage.width, maxH / pngImage.height, 1);
    const drawW = pngImage.width * scale;
    const drawH = pngImage.height * scale;

    page.drawImage(pngImage, {
      x: MARGIN,
      y: y - drawH,
      width: drawW,
      height: drawH,
    });

    drawFooter(page);
  }

  return Buffer.from(await doc.save());
}
